-- Removendo as tabelas existentes
DROP TABLE FINTECH_CONTAS;
DROP TABLE FINTECH_CLIENTES;

-- Criação da tabela FINTECH_CLIENTES
CREATE TABLE FINTECH_CLIENTES (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(11) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    TELEFONE VARCHAR2(20) NOT NULL,
    ENDERECO VARCHAR2(200) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL CHECK (STATUS IN (0,1)),
    DATA_CRIACAO TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Criação de índices
CREATE INDEX IDX_FINTECH_CLIENTES_CPF ON FINTECH_CLIENTES(CPF);
CREATE INDEX IDX_FINTECH_CLIENTES_EMAIL ON FINTECH_CLIENTES(EMAIL);
CREATE INDEX IDX_FINTECH_CLIENTES_STATUS ON FINTECH_CLIENTES(STATUS);

-- Criação da tabela FINTECH_CONTAS

CREATE TABLE FINTECH_CONTAS (ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENTE_ID NUMBER(19) NOT NULL,
    TIPO_CONTA NUMBER(2) NOT NULL, -- 1 = Corrente, 2 = Poupança
    SALDO NUMBER(15, 2) DEFAULT 0 NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL CHECK (STATUS IN (0,1)), -- 0 = Inativo, 1 = Ativo
    DATA_CRIACAO TIMESTAMP DEFAULT SYSDATE NOT NULL,

    CONSTRAINT FK_CONTAS_CLIENTE FOREIGN KEY (CLIENTE_ID)
        REFERENCES FINTECH_CLIENTES(ID)
        ON DELETE CASCADE
);

