-- Criação da tabela FINTECH_CLIENTES
CREATE TABLE FINTECH_CLIENTES (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(11) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    TELEFONE VARCHAR2(20) NOT NULL,
    ENDERECO VARCHAR2(200) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    STATUS NUMBER(1) DEFAULT 1 NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT SYSDATE NOT NULL,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- Comentários nas colunas
COMMENT ON COLUMN FINTECH_CLIENTES.ID IS 'Identificador único do cliente';
COMMENT ON COLUMN FINTECH_CLIENTES.NOME IS 'Nome completo do cliente';
COMMENT ON COLUMN FINTECH_CLIENTES.CPF IS 'CPF do cliente (apenas números)';
COMMENT ON COLUMN FINTECH_CLIENTES.EMAIL IS 'Email do cliente';
COMMENT ON COLUMN FINTECH_CLIENTES.TELEFONE IS 'Telefone do cliente';
COMMENT ON COLUMN FINTECH_CLIENTES.ENDERECO IS 'Endereço completo do cliente';
COMMENT ON COLUMN FINTECH_CLIENTES.DATA_NASCIMENTO IS 'Data de nascimento do cliente';
COMMENT ON COLUMN FINTECH_CLIENTES.STATUS IS 'Status do cliente (1-Ativo, 0-Inativo)';
COMMENT ON COLUMN FINTECH_CLIENTES.DATA_CRIACAO IS 'Data de criação do registro';
COMMENT ON COLUMN FINTECH_CLIENTES.DATA_ATUALIZACAO IS 'Data da última atualização do registro';

-- Criação de índices
CREATE INDEX IDX_FINTECH_CLIENTES_CPF ON FINTECH_CLIENTES(CPF);
CREATE INDEX IDX_FINTECH_CLIENTES_EMAIL ON FINTECH_CLIENTES(EMAIL);
CREATE INDEX IDX_FINTECH_CLIENTES_STATUS ON FINTECH_CLIENTES(STATUS);

-- Trigger para atualizar DATA_ATUALIZACAO
CREATE OR REPLACE TRIGGER TRG_FINTECH_CLIENTES_UPDATE
BEFORE UPDATE ON FINTECH_CLIENTES
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := SYSDATE;
END;
/ 